config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  root to: 'users#index'
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  # namespace :api do
  #   get '/users/:author_id/posts', to: 'posts#index'
  #   post '/comments', to: 'comments#create'
  #   get '/users/:author_id/posts/:post_id/comments', to: 'comments#index'
  # end

  namespace :api do
    resources :users do
      resources :posts do
        resources :comments
      end
    end
  end

  resources :users do
    resources :posts do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  get "/users/:user_id/posts/:post_id/comments/new", to: "comments#new", as: 'new_comment'
  post "/users/:user_id/posts/:post_id/comments", to: "comments#create", as: 'comments'
  delete "/users/:user_id/posts/:post_id/comments/:id", to: "comments#destroy", as: 'comment'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all

    return unless user.present?

    can :manage, Post, author_id: user.id
    can :manage, Comment, author_id: user.id
    can :create, Post
    can :create, Comment

    return unless user.admin?

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post

  after_save :update_comment_counter

  def update_comment_counter
    # post.update(comments_counter: post.comments.count)
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post

  after_save :update_like_counter

  private

  def update_like_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments
  has_many :likes

  after_save :update_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true

  def five_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :posts, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true

  def admin?
    roles == 'admin'
  end

  def three_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController
end

app/controllers/api/posts_controller.rb
module Api
  class Api::PostsController < ApiController
    def index
      @user = User.find(params[:user_id])
      @posts = Post.where(author_id: @user.id).includes(:comments)
      render json: @posts
    end

    def show
      @posts = Post.find(params[:id])
      render json: @posts
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.includes(:posts).find(params[:author_id])
    @post = @user.posts
    @comments = Comment.where(posts: @post)

    respond_to do |format|
      format.html
      format.json { render json: @comments }
    end
  end

  def new
    @user = User.find(params[:author_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(author: current_user, **comment_params)
    puts @comment
    puts comment_params
    puts @post
    if @comment.save
      redirect_to "/users/#{current_user.id}/posts", notice: 'Comment Created Successfully'
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    @like = post.likes.new(author: current_user)
    if @like.save
      redirect_to user_post_likes_path(user_id: current_user.id, post_id: post.id)
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:author_id])
    @posts = @user.posts

    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  def show
    @user = User.find(params[:author_id])
    @post = @user.posts.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.comments_counter = 0
    @post.likes_counter = 0
    @post.author_id = current_user.id
    if @post.save
      redirect_to user_posts_path, notice: 'Post Created Successfully'
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_posts_path(current_user), notice: 'Post Deleted Successfully'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render 'devise/sessions/new'
  end

  def destroy
    sign_out(current_user)
    redirect_to new_user_session_path, notice: 'You have been signed out successfully.'
  end
end

app/controllers/users_controller.rb
require 'cancancan'
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    return unless @user.save

    redirect_to action: 'list'
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    return unless @user.update_attributes(user_params)

    redirect_to action: 'show', id => @user
  end

  def delete
    User.find(params[:id]).destroy
    redirect_to action: 'list'
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/api/api_helper.rb
module Api::ApiHelper
end

app/helpers/api/comments_helper.rb
module Api::CommentsHelper
end

app/helpers/api/posts_helper.rb
module Api::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/posts/index.html.erb
<p>Posts by user</p>
<%= flash[:notice]%>
<div class="posts-container">
  <div class="img-post">
          <img src="<%= @user.photo %>"/>
      <div class="name-posts">
          <div class="name"><%= @user.name %></div>
          Number of posts: <%= @user.posts_counter %>
      </div>
      Bio: <%= @user.bio%>
  </div>
 
  <ul class="posts">
    <% @user.posts.includes(:author, :comments).each do |post| %>
        <a href="<%= user_post_path(@user, post) %>">
        <li class="user-posts" ">
            
                <h3><%= link_to "Post ##{post.id}", user_post_path(@user, post)%></h3>
                <p><%=post.title%></p>
                <p><%=post.text%></p>
                <div class="com-like">Comments: <%= post.comments_counter%> Likes: <%= post.likes_counter%></div>
            
        </li>
        </a>
        <% post.five_recent_comments.each do |comment| %>
            <div class="user-comments">
              <div>Comment: <%= comment.text %></div>
            </div>
          <% end %>
    <% end %>
  </ul>

  <button class='see-all, pagination' type='button'>Pagination</button>
  # <% if @current_user && @current_user.id == @user.id %>
  #   <button class="btn_add_new_post">
  #     <%= link_to 'Add new Post', new_user_post_path(user_id: @user.id) %>
  #   </button>
  # <% end %>
</div>

app/views/posts/new.html.erb
<div class = 'new_post'>
    <h2>Create New Post</h2>
    <div class = "back_to_posts">
        <%= link_to 'Back to Posts', user_posts_path %>
    </div>
    <div class = "add_new_post">
        <%= form_with model: @post, url: user_posts_path do |form| %>
            <%= form.label :title %>
            <div class = "new_post_title">
                <%= form.text_field :title %>
            </div>
            <div class = "new_post_text">
                <%= form.label :text %>
                <%= form.text_area :text %>
            </div>
            <div class = "btn_new_post">
                <%= form.submit class: 'btn_create_post' %>
            </div>
        <% end %>
    </div>
</div>

app/views/posts/show.html.erb
<div class="post-of-user">
        <div class="post-comment">        
            <div class="post-user">
                Post <%= @post.id%> by <%= @user.name %><br/>
                Title: <%= @post.title%> 
            </div>
            <div>Comments: <%= @post.comments_counter%> Likes: <%= @post.likes_counter%></div>
            
            <% if can? :destroy, @post %>
                <%= form_with(url: user_post_path(@post.author, @post), method: :delete) do |f| %>
                <%= f.submit 'Delete Post' %>
            <% end %>
        <% end %>
        </div>
        <div class="post-text">Comment: <%= @post.text %></div>
        
        <div class = "btn_comment_like">
            <button class = 'btn_add_comment'><%= link_to 'Add Comment', new_user_post_comment_path(@user, @post)%></button>
            <%= form_with model: @likes do |form| %>
                <%= form.submit "Add Likes", class: 'btn_add_likes' %>
            <% end %>
        </div>
        
        <div>
            <% @post.five_recent_comments.each do |comment| %>
                <div class="user-comments">
                <div>Comment: <%= comment.text %></div>
                </div>
                <% if can? :destroy, comment %>
                    <%= form_with(url: comment_path(@user, @post, comment), method: :delete) do |f| %>
                    <%= f.submit 'Delete Comment' %>
                    <% end %>
                <% end %>
            <% end %>
        </div>

        <div>
            <button id="home-button" class = 'btn_add_comment'><%= link_to 'Home', root_path%></button>
        </div>

        
</div>